In [1]:
import pandas as pd
import numpy as np

C:\Users\DMC-L001\Anaconda3\lib\site-packages\gensim\utils.py:1167: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")


In [3]:
xl = pd.ExcelFile("80s.xlsx")
xl.sheet_names

['80s']

In [5]:
df = xl.parse("80s")
df.head()

EVALUACION                                      Comentariomin
0           5  totalmente satisfecho x q resolvieron mi  cons...
1           5                     la atencion fue rapida y clara
2           4                                 me atendieron bien
3           5                         fue muy rapido la atencion
4           5  por que me atendieron muy amablemente con buen...

In [7]:
df.shape

(13290, 2)

In [9]:
#tenemos que transformar la data a string que nos interesa
#primera forma
df["Comentariomin"].str.encode("utf-8")

0        b'totalmente satisfecho x q resolvieron mi  co...
1                        b'la atencion fue rapida y clara'
2                                    b'me atendieron bien'
3                            b'fue muy rapido la atencion'
4        b'por que me atendieron muy amablemente con bu...
5                 b'me atendieron bien con mucha atencion'
6        b'la atencion de las se\xc3\xb1oritas de la en...
7        b'porque hay varios cajerosas es una agencia r...
8                                        b'buena atencion'
9         b'la atencion fue rapida y no toma mucho tiempo'
10                         b'la atencion a sido excelente'
11                                  b'buena atencion caja'
12                                b'su atencion y rapidez'
13                     b'la atencion fue rapida y precisa'
14       b'por q su personal es muy eficiente y hacen a...
15       b'porque la atencion fue bastante cordial la t...
16       b'porque recibi una atencion amable desde que .

In [10]:
#segunda forma
df["Comentariomin"].values

array(['totalmente satisfecho x q resolvieron mi  consulta y x q la atencion fue muy buena y mis dudas fueron respondidas',
       'la atencion fue rapida y clara', 'me atendieron bien', ...,
       'la demora en la atencion en ventanilla',
       'que atiendan en todas las cajas para que el movimiento de clientes sea mas rapido',
       'mejor trato por parte de la persona que atiende'], dtype=object)

In [6]:
#tercera forma
pd.DataFrame(df["Comentariomin"])

Comentariomin
0      totalmente satisfecho x q resolvieron mi  cons...
1                         la atencion fue rapida y clara
2                                     me atendieron bien
3                             fue muy rapido la atencion
4      por que me atendieron muy amablemente con buen...
5                  me atendieron bien con mucha atencion
6      la atencion de las señoritas de la entrada fue...
7      porque hay varios cajerosas es una agencia rel...
8                                         buena atencion
9          la atencion fue rapida y no toma mucho tiempo
10                          la atencion a sido excelente
11                                   buena atencion caja
12                                 su atencion y rapidez
13                      la atencion fue rapida y precisa
14     por q su personal es muy eficiente y hacen ava...
15     porque la atencion fue bastante cordial la tra...
16     porque recibi una atencion amable desde que in...
17     por que resolvieron mis dudas me dieron buenas...
18                  atencion rapida eficiente amabilidad
19     en esta ocasion la atencion fue muy rapida muy...
20                   buena calidad y rapidez de atencion
21                                         bien recibido
22     es la primera vez que me acerco a esta agencia...
23                                    excelente atencion
24                                       atencion rapida
25                              conforme con la atencion
26     la amabilidad y paciencia al explicar mi  caso...
27     fue la atencion mas rapida y con una buena gui...
28                       orden   rapidez en la atencion 
29     el trato fue amable y cordial como corresponde...
...                                                  ...
13260            me asusto el chico que tiene una tablet
13261  no esperar tanto tiempo para ser atendido  no ...
13262                     mayor velocidad en la atencion
13263  para disposicion en efectivo el sistema arroja...
13264   lo que pasa es que el sistema de plataforma e...
13265               mas cajeros y atencion en ventanilla
13266  yo normalmente retiro por cajero en moneda dol...
13267         tener mayor consideracion con preferencial
13268                       demorar menos en la atencion
13269  que sean mas rapidos en la atencion que habili...
13270                                                gjh
13271  porque siempre que hago alguna operacion y des...
13272                                mas rapida atencion
13273  que me brinden en plataforma mas informacion s...
13274  el tramite que realice demoro debido a problem...
13275  si estuvo satisfecho sino que a mi celular lle...
13276  demora en la atencion al cliente habian  venta...
13277        siempre e discrepado la forma como atienden
13278  se acerco mi papa para ver el tema del prestam...
13279  que hayan mas ventanillas en la calle se forma...
13280       aclarar las dudas que tengo sobre mi tarjeta
13281  creo que seria bueno si me regalan plata estar...
13282  mas promotores en ventanilla las colas son muy...
13283                               cogero no funcionaba
13284  la persona que me atendio no se mostro complet...
13285  hice un abono de  la cual no me comunico que p...
13286                                           atencion
13287             la demora en la atencion en ventanilla
13288  que atiendan en todas las cajas para que el mo...
13289    mejor trato por parte de la persona que atiende

[13290 rows x 1 columns]

In [18]:
#Guardamos los datos transformados
np.savetxt("comments.txt", pd.DataFrame(df["Comentariomin"].values), fmt='%s', encoding="utf-8")

In [19]:
from gensim.models import word2vec
sentences = word2vec.Text8Corpus("comments.txt") #la función corpus necesita que la data este en utf-8
sentences

In [20]:
#generamos nuestro modelo 
model = word2vec.Word2Vec(sentences, size=200,min_count=2)#vector de tamaño 200

In [21]:
model["bueno"]

C:\Users\DMC-L001\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  if __name__ == '__main__':


array([-6.88134646e-03, -1.47410035e-01,  4.24128681e-01,  3.34832370e-01,
        1.68207511e-01,  6.34761453e-01, -1.43569052e-01, -2.05369145e-01,
       -1.39561415e-01,  1.21010788e-01,  1.85340255e-01,  2.62631387e-01,
       -3.99552673e-01, -1.17734432e-01,  1.56459957e-01, -3.22768569e-01,
       -1.30563349e-01, -2.72482261e-02, -3.90807837e-02,  1.25530779e-01,
       -2.08012670e-01, -6.29800379e-01,  2.54054606e-01, -9.15693268e-02,
       -1.21408831e-02, -1.06514059e-01,  2.79475935e-02,  8.04604813e-02,
       -1.65321156e-01,  1.21617660e-01, -2.02554185e-02, -1.24445051e-01,
       -1.96369112e-01, -3.86710800e-02, -3.66897434e-01,  9.67540517e-02,
        2.27112144e-01,  1.96212053e-01, -2.13544909e-02,  2.82634169e-01,
       -3.54511559e-01, -2.81685404e-02,  1.80983752e-01, -2.35572189e-01,
       -9.03952047e-02, -4.61446464e-01,  7.09211305e-02,  7.23422021e-02,
        1.45496607e-01,  1.92977622e-01,  1.99721158e-01,  1.18781000e-01,
       -2.67112076e-01,  

In [25]:
len(model.wv.vocab)#para saber cuantas palabras tiene nuestro modelo

4964

In [126]:
def getFV(document):#recibe un documento
    #a ese documento, que es un comentario especifico, lo tekenizamos con split
    words=document.split()
    s=np.zeros(200)
    k=1
    for w in words:#a traves del for vamos sumando mientras la palabra está en el vocabulario
        if w in model.wv.vocab:
            s=s+model[w]
            k=k+1
    
    return s/k # devuelve un vector caracteristico por comentario

In [29]:
#seleccionar los comentarios positivos
df_positives = df[df["EVALUACION"]>=4] #para tener los datos en si (y no solo true or false) lo coloco dentro de otro dataframe
df_positives.shape

(6595, 2)

In [30]:
#seleccionar los comentarios negativos
df_negatives = df[df["EVALUACION"]<4] 
df_negatives.shape

(6695, 2)

In [164]:
#usaremos solamente 800 datos para train
positive_train = df_positives[:5000].sample(800)
positive_train.head()

EVALUACION                                      Comentariomin
1330           5  porque soy muy amables con la ayuda y la atenc...
278            5                             menos descongestionada
4545           5     pude realizar todas las transacciones deseadas
2679           5  un excente trato al cliente buena y oportuna i...
1184           5                   buena atencion y dudas aclaradas

In [179]:
negative_train = df_negatives[:5000].sample(800)
negative_train.head()

EVALUACION                                      Comentariomin
10572           2  el cajero de depostos estaba malogrado y ningu...
11374           3                                     buena atencion
9004            1  ya van  tarjetas que voy sacando cual resulta ...
9229            3                         mayor vocacion de servicio
6831            2  no tenian sistema la orientadora me decia que ...

In [166]:
#usaremos solamente 200 datos para test
positive_test = df_positives[:5000].sample(200)
positive_test.head()

EVALUACION                                      Comentariomin
1247           4  por la buena atencion aunque no tuve buen resu...
872            5  por la atencion rapida y eficiente del persona...
602            5                                atencion muy rapida
4515           4             no hubo cola y el trato fue muy amable
3480           5                        la atencion fue de lo mejor

In [167]:
negative_test = df_negatives[:5000].sample(200)
negative_test.head()

EVALUACION                                      Comentariomin
7589            2  fui a pedir que me ayuden a solucionar un prob...
7552            2  pese a ser una cliente de largo tiempome ha de...
10861           2                        mala asesoria en plataforma
9725            3  ser totalmente informado recibi la renovacion ...
6813            2  veo  cajas pero siempre abren solo  o  tomando...

In [180]:
v_positive_train = getFV(positive_train["Comentariomin"].values[0])
#construimos el vetor caracteristico para los 4 conjuntos y todos sus elementos
v_positive_train = positive_train["Comentariomin"].apply(lambda x: getFV(x))
v_positive_train = np.matrix(v_positive_train.tolist())
v_positive_train.shape

C:\Users\DMC-L001\Anaconda3\lib\site-packages\ipykernel\__main__.py:8: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).


(800, 200)

In [181]:
v_negative_train = negative_train["Comentariomin"].apply(lambda x: getFV(x)).as_matrix(columns=None)
v_negative_train = np.matrix(v_negative_train.tolist())
v_negative_train.shape

C:\Users\DMC-L001\Anaconda3\lib\site-packages\ipykernel\__main__.py:8: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).


(800, 200)

In [182]:
v_positive_test = positive_test["Comentariomin"].apply(lambda x: getFV(x))
v_positive_test = np.matrix(v_positive_test.tolist())
v_positive_test.shape

C:\Users\DMC-L001\Anaconda3\lib\site-packages\ipykernel\__main__.py:8: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).


(200, 200)

In [183]:
v_negative_test = negative_test["Comentariomin"].apply(lambda x: getFV(x))
v_negative_test = np.matrix(v_negative_test.tolist())
v_negative_test

C:\Users\DMC-L001\Anaconda3\lib\site-packages\ipykernel\__main__.py:8: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).


matrix([[-0.02593654, -0.16812548,  0.2789196 , ...,  0.06996994,
         -0.09652223,  0.45712714],
        [-0.03213248, -0.13451513,  0.28686782, ...,  0.05696358,
         -0.04482666,  0.43903045],
        [ 0.06017977, -0.02077689,  0.3085671 , ..., -0.1048305 ,
         -0.01368178,  0.3603955 ],
        ...,
        [ 0.02600698, -0.04469763,  0.40998596, ..., -0.08166715,
          0.04110167,  0.46944109],
        [-0.0316714 , -0.15631191,  0.27438112, ...,  0.09529478,
         -0.05211977,  0.45507052],
        [-0.04292275, -0.13250409,  0.29137684, ...,  0.05855245,
         -0.06283559,  0.44495171]])

In [ ]:
#ahora teniendo los vectores caracteristicos, enviamos a entrenar los datos

In [189]:
from sklearn import svm
from sklearn import datasets

clasificador = svm.SVC(gamma=0.0001,C=100)#construimos el objeto del clasificador

#entrenamos
X_train = np.concatenate((v_positive_train, v_negative_train), axis=0)
Y_train= np.concatenate((positive_train["EVALUACION"].values, negative_train["EVALUACION"].values), axis=0)
clasificador.fit(X_train,Y_train)

SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.0001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [192]:
np.concatenate((positive_train["EVALUACION"].values, negative_train["EVALUACION"].values), axis=0)

array([5, 5, 5, ..., 3, 2, 2], dtype=int64)

In [194]:
#TEST
X_test =np.concatenate((v_positive_test, v_negative_test), axis=0)
clasificador.predict(X_test)

array([5, 5, 5, 5, 5, 3, 5, 5, 5, 5, 3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 3, 5, 5, 3, 3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 3, 5, 5, 5, 3, 5, 5, 5, 5, 5, 3, 3, 5, 3, 3, 5, 5, 5, 5, 5,
       5, 5, 3, 5, 3, 5, 5, 5, 5, 3, 5, 5, 5, 3, 5, 5, 5, 3, 5, 3, 5, 5,
       5, 5, 5, 3, 2, 5, 5, 3, 5, 5, 3, 5, 5, 3, 5, 3, 5, 5, 3, 5, 3, 3,
       5, 5, 3, 5, 5, 5, 3, 5, 5, 5, 5, 5, 2, 5, 5, 3, 5, 5, 3, 5, 5, 5,
       5, 5, 5, 5, 3, 5, 5, 2, 5, 5, 5, 5, 5, 3, 5, 5, 3, 5, 5, 3, 3, 5,
       5, 3, 5, 5, 3, 5, 5, 5, 5, 5, 5, 3, 3, 5, 5, 5, 5, 5, 5, 5, 3, 5,
       5, 3, 3, 5, 5, 5, 5, 3, 5, 5, 3, 5, 5, 5, 5, 5, 3, 5, 5, 5, 5, 5,
       5, 5, 2, 3, 3, 3, 3, 3, 3, 5, 3, 3, 3, 3, 3, 3, 3, 3, 5, 3, 5, 3,
       5, 3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 2, 5, 5, 5, 3, 5, 3, 2, 3, 3, 5,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 3, 3, 5, 3, 3, 3, 3, 3, 3, 3, 3,
       5, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 5, 3, 3, 5, 5, 3, 3, 3, 5,
       3, 2, 3, 3, 5, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,

In [197]:
y_true = np.concatenate((positive_test["EVALUACION"].values, negative_test["EVALUACION"].values), axis=0)
y_pred = clasificador.predict(X_test)

In [198]:
from sklearn.metrics import accuracy_score
accuracy_score(y_true, y_pred)

0.4525

In [203]:
#probamos la predicción
cm = "Mala atencion"
test_cm = getFV(cm)

C:\Users\DMC-L001\Anaconda3\lib\site-packages\ipykernel\__main__.py:8: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).


In [204]:
test_cm = np.array(test_cm).reshape((1, len(test_cm)))
clasificador.predict(test_cm)

array([5], dtype=int64)