# Sesión 2. Inferencia Estadística

# Distribuciones de probabilidad para una variable aleatoria discreta

In [48]:
# Importar la librería NumPy
import numpy as np

In [49]:
# Importar la librería Pandas desde Python.
import pandas as pd

In [50]:
# Importar datos en formato xls.
data_hipotecas = pd.read_excel('C:/Users/user/Documents/Python_Analytics/hipotecas.xlsx')

In [51]:
data_hipotecas.head()

Tienda  ID_VENDEDOR  NRO_HIPO
0       5            1         2
1       5            2         6
2       5            3         5
3       5            4         7
4       5            5         1

In [52]:
data_hipotecas.describe()

Tienda  ID_VENDEDOR     NRO_HIPO
count  9798.000000  9798.000000  9798.000000
mean      2.988263  4899.500000     4.020821
std       1.417661  2828.583303     2.777624
min       1.000000     1.000000     0.000000
25%       2.000000  2450.250000     2.000000
50%       3.000000  4899.500000     4.000000
75%       4.000000  7348.750000     6.000000
max       5.000000  9798.000000    70.000000

In [53]:
data_hipotecas[data_hipotecas['Tienda']==1].describe()

Tienda  ID_VENDEDOR     NRO_HIPO
count  1972.0  1972.000000  1972.000000
mean      1.0  8812.500000     4.111055
std       0.0   569.411685     3.423935
min       1.0  7827.000000     0.000000
25%       1.0  8319.750000     2.000000
50%       1.0  8812.500000     4.000000
75%       1.0  9305.250000     6.000000
max       1.0  9798.000000    70.000000

In [54]:
data_hipotecas[data_hipotecas['Tienda']==2].describe()

Tienda  ID_VENDEDOR     NRO_HIPO
count  2026.0  2026.000000  2026.000000
mean      2.0  6813.500000     3.978776
std       0.0   585.000142     2.580849
min       2.0  5801.000000     0.000000
25%       2.0  6307.250000     2.000000
50%       2.0  6813.500000     4.000000
75%       2.0  7319.750000     6.000000
max       2.0  7826.000000     8.000000

In [55]:
data_hipotecas[data_hipotecas['Tienda']==3].describe()

Tienda  ID_VENDEDOR     NRO_HIPO
count  1906.0  1906.000000  1906.000000
mean      3.0  4847.500000     4.026233
std       0.0   550.359125     2.582059
min       3.0  3895.000000     0.000000
25%       3.0  4371.250000     2.000000
50%       3.0  4847.500000     4.000000
75%       3.0  5323.750000     6.000000
max       3.0  5800.000000     8.000000

In [56]:
data_hipotecas[data_hipotecas['Tienda']==4].describe()

Tienda  ID_VENDEDOR     NRO_HIPO
count  1933.0  1933.000000  1933.000000
mean      4.0  2928.000000     3.978789
std       0.0   558.153354     2.603164
min       4.0  1962.000000     0.000000
25%       4.0  2445.000000     2.000000
50%       4.0  2928.000000     4.000000
75%       4.0  3411.000000     6.000000
max       4.0  3894.000000     8.000000

In [57]:
data_hipotecas[data_hipotecas['Tienda']==5].describe()

Tienda  ID_VENDEDOR     NRO_HIPO
count  1961.0  1961.000000  1961.000000
mean      5.0   981.000000     4.009689
std       0.0   566.236258     2.592652
min       5.0     1.000000     0.000000
25%       5.0   491.000000     2.000000
50%       5.0   981.000000     4.000000
75%       5.0  1471.000000     6.000000
max       5.0  1961.000000     8.000000

# Distribución Binomial

In [58]:
from scipy.stats import binom
import matplotlib.pyplot as plt

In [59]:
x=3
n=10
p=0.5
prob = binom.cdf(x, n, p)
prob

0.17187499999999994

In [60]:
pd=1-prob
pd

0.828125

# Distribución Poisson

In [61]:
# Importar datos en formato xls.
import pandas as pd
autos_averias = pd.read_excel('C:/Users/user/Documents/Python_Analytics/averias_autos.xlsx')

In [62]:
autos_averias.head()

Marca  nro_averias
0  Dodge            3
1   Ford            3
2   Ford            2
3  Dodge            1
4  Dodge            2

In [63]:
lambda1=autos_averias[autos_averias['Marca']=='Dodge'].groupby(['Marca'])['nro_averias'].mean()
lambda1

Marca
Dodge    1.967645
Name: nro_averias, dtype: float64

In [64]:
lambda2=autos_averias[autos_averias['Marca']=='Ford'].groupby(['Marca'])['nro_averias'].mean()
lambda2

Marca
Ford    2.020821
Name: nro_averias, dtype: float64

In [65]:
from scipy.stats import poisson
import matplotlib.pyplot as plt

In [66]:
x=0
mu=lambda1
prob1 = poisson.cdf(x, mu)
prob1

array([ 0.13978562])

In [67]:
x=0
mu=lambda2
prob2 = poisson.cdf(x, mu)
prob2

array([ 0.13254658])

# Estandarización de los datos

In [73]:
# Importar datos en formato xls.
import pandas as pd
churners_data = pd.read_excel('C:/Users/user/Documents/Python_Analytics/Churners.xlsx')

In [74]:
churners_data.head()

ID  EDAD       SEXO    CIVIL  HIJOS  INGRESO                    AUTO  \
0   0    57   Femenino   Casado      2  27535.3     Es dueño de un auto   
1   4    68   Femenino   Casado      2  81000.9  No es dueño de un auto   
2   8    34  Masculino  Soltero      0  87467.1     Es dueño de un auto   
3  10    60  Masculino   Casado      2  83220.6  No es dueño de un auto   
4  13    28   Femenino   Casado      2  20850.4  No es dueño de un auto   

        CHURN  
0  Voluntario  
1  Voluntario  
2      Actual  
3  Voluntario  
4  Voluntario

In [75]:
churners_data_0=churners_data[churners_data['CHURN']=='Voluntario']

In [76]:
churners_data_0.head()

ID  EDAD       SEXO    CIVIL  HIJOS   INGRESO                    AUTO  \
0   0    57   Femenino   Casado      2  27535.30     Es dueño de un auto   
1   4    68   Femenino   Casado      2  81000.90  No es dueño de un auto   
3  10    60  Masculino   Casado      2  83220.60  No es dueño de un auto   
4  13    28   Femenino   Casado      2  20850.40  No es dueño de un auto   
6  19    87   Femenino  Soltero      2   3776.12  No es dueño de un auto   

        CHURN  
0  Voluntario  
1  Voluntario  
3  Voluntario  
4  Voluntario  
6  Voluntario

In [77]:
churners_ing=churners_data_0['INGRESO']

In [78]:
churners_ing.head()

0    27535.30
1    81000.90
3    83220.60
4    20850.40
6     3776.12
Name: INGRESO, dtype: float64

In [79]:
import numpy as np

In [80]:
from scipy import stats

In [81]:
score_churners = stats.zscore(churners_ing) # estandarizamos los datos

In [82]:
pd.DataFrame(score_churners).head()

0
0 -0.728985
1  1.142023
2  1.219701
3 -0.962921
4 -1.560429

In [83]:
churners_ing.head()

0    27535.30
1    81000.90
3    83220.60
4    20850.40
6     3776.12
Name: INGRESO, dtype: float64

In [84]:
pd.DataFrame(churners_ing).mean()

INGRESO    48366.650984
dtype: float64

In [85]:
pd.DataFrame(churners_ing).std()

INGRESO    28603.710304
dtype: float64

In [86]:
pd.DataFrame(score_churners).std()

0    1.000976
dtype: float64

In [87]:
pd.DataFrame(score_churners).std()

0    1.000976
dtype: float64

In [88]:
z=(50000-churners_ing.mean())/churners_ing.std()
z

0.05710269745536449

In [89]:
prob = 1 - stats.norm.cdf(z)
prob

0.47723169383645603

In [90]:
churners_data_1=churners_data[churners_data['CHURN']=='Actual']
churners_data_1.head()

ID  EDAD       SEXO    CIVIL  HIJOS  INGRESO                    AUTO  \
2    8    34  Masculino  Soltero      0  87467.1     Es dueño de un auto   
5   17    52  Masculino  Soltero      0  84112.6  No es dueño de un auto   
8   22    76  Masculino   Casado      2  30933.6     Es dueño de un auto   
11  28    90   Femenino   Casado      0  91620.6  No es dueño de un auto   
12  30    62  Masculino  Soltero      0  96501.9     Es dueño de un auto   

     CHURN  
2   Actual  
5   Actual  
8   Actual  
11  Actual  
12  Actual

In [91]:
nchurners_ing=churners_data_1['INGRESO']

In [92]:
score_nchurners = stats.zscore(nchurners_ing) # estandarizamos los datos

In [93]:
z=(50000-nchurners_ing.mean())/nchurners_ing.std()
z

-0.07263464252532714

In [94]:
prob = 1 - stats.norm.cdf(z)
prob

0.52895157061581521

# T test

In [100]:
from __future__ import print_function

import numpy as np
from scipy.stats import ttest_ind, ttest_ind_from_stats
from scipy.special import stdtr

In [101]:
churners_data = pd.read_excel('C:/Users/user/Documents/Python_Analytics/Churners.xlsx')

In [102]:
churners_data.head()

ID  EDAD       SEXO    CIVIL  HIJOS  INGRESO                    AUTO  \
0   0    57   Femenino   Casado      2  27535.3     Es dueño de un auto   
1   4    68   Femenino   Casado      2  81000.9  No es dueño de un auto   
2   8    34  Masculino  Soltero      0  87467.1     Es dueño de un auto   
3  10    60  Masculino   Casado      2  83220.6  No es dueño de un auto   
4  13    28   Femenino   Casado      2  20850.4  No es dueño de un auto   

        CHURN  
0  Voluntario  
1  Voluntario  
2      Actual  
3  Voluntario  
4  Voluntario

In [103]:
churners_data_0=churners_data[churners_data['CHURN']=='Voluntario']

In [104]:
churners_edad=churners_data_0['EDAD']

In [105]:
churners_data_1=churners_data[churners_data['CHURN']=='Actual']

In [106]:
nchurners_edad=churners_data_1['EDAD']

In [107]:
# Use scipy.stats.ttest_ind.
t, p = ttest_ind(churners_edad, nchurners_edad, equal_var=False)
print("ttest_ind:            t = %g  p = %g" % (t, p))

ttest_ind:            t = 2.12927  p = 0.0334498


In [108]:
p_valor=(2-p)/2
p_valor

0.9832750870595256

In [109]:
churners_edad.mean()

59.113060428849906

In [110]:
nchurners_edad.mean()

56.42908653846154

In [111]:
import numpy as np
import scipy as sp
import scipy.stats

def mean_confidence_interval(data, confidence=0.95):
    a = 1.0*np.array(data)
    n = len(a)
    m, se = np.mean(a), scipy.stats.sem(a)
    h = se * sp.stats.t._ppf((1+confidence)/2., n-1)
    return m, m-h, m+h

# Intervalos de Confianza

In [112]:
churners_ing.head()

0    27535.30
1    81000.90
3    83220.60
4    20850.40
6     3776.12
Name: INGRESO, dtype: float64

In [113]:
import numpy as np
import scipy as sp
import scipy.stats

def mean_confidence_interval(data, confidence=0.95):
    a = 1.0*np.array(data)
    n = len(a)
    m, se = np.mean(a), scipy.stats.sem(a)
    h = se * sp.stats.t._ppf((1+confidence)/2., n-1)
    return m, m-h, m+h

In [114]:
mean_confidence_interval(churners_ing,0.95)

(48366.650984405453, 45885.577533845033, 50847.724434965872)

# Coeficiente de correlación

In [115]:
churners_data_0.head()

ID  EDAD       SEXO    CIVIL  HIJOS   INGRESO                    AUTO  \
0   0    57   Femenino   Casado      2  27535.30     Es dueño de un auto   
1   4    68   Femenino   Casado      2  81000.90  No es dueño de un auto   
3  10    60  Masculino   Casado      2  83220.60  No es dueño de un auto   
4  13    28   Femenino   Casado      2  20850.40  No es dueño de un auto   
6  19    87   Femenino  Soltero      2   3776.12  No es dueño de un auto   

        CHURN  
0  Voluntario  
1  Voluntario  
3  Voluntario  
4  Voluntario  
6  Voluntario

In [116]:
churners_eval=churners_data_0[['EDAD','INGRESO']]

In [117]:
churners_eval.head()

EDAD   INGRESO
0    57  27535.30
1    68  81000.90
3    60  83220.60
4    28  20850.40
6    87   3776.12

In [118]:
from scipy import stats

In [122]:
stats.pearsonr(churners_data_0['EDAD'], churners_data_0['INGRESO'])

(0.2063985658696835, 2.4257223178798058e-06)

In [ ]:
## Evaluamos la normalidad de la Edad

In [123]:
import scipy.stats as stats
stats.normaltest(churners_data_0['EDAD'])

NormaltestResult(statistic=97.154050208678868, pvalue=8.0032438562828799e-22)

In [124]:
stats.normaltest(churners_data_0['INGRESO'])

NormaltestResult(statistic=281.1563740854275, pvalue=8.8648030519480659e-62)

In [78]:
stats.spearmanr(churners_data_0['EDAD'], churners_data_0['INGRESO'])

SpearmanrResult(correlation=0.1940862273596578, pvalue=9.5374822389871346e-06)

# Prueba de Independencia

In [81]:
churners_data_0.head()

ID  EDAD       SEXO    CIVIL  HIJOS   INGRESO                    AUTO  \
0   0    57   Femenino   Casado      2  27535.30     Es dueño de un auto   
1   4    68   Femenino   Casado      2  81000.90  No es dueño de un auto   
3  10    60  Masculino   Casado      2  83220.60  No es dueño de un auto   
4  13    28   Femenino   Casado      2  20850.40  No es dueño de un auto   
6  19    87   Femenino  Soltero      2   3776.12  No es dueño de un auto   

        CHURN  
0  Voluntario  
1  Voluntario  
3  Voluntario  
4  Voluntario  
6  Voluntario

In [95]:
a=churners_data['CHURN']
b=churners_data['SEXO']
voters = pd.DataFrame({"churn":a, 
                       "sexo":b})

voter_tab = pd.crosstab(voters.churn, voters.sexo, margins = True)

In [96]:
voter_tab

sexo        Femenino  Masculino   All
churn                                
Actual           250        582   832
Voluntario       423         90   513
All              673        672  1345

In [97]:
sex_churn = np.array([[250, 582],[423,90]])
sex_churn

array([[250, 582],
       [423,  90]])

In [99]:
stats.chi2_contingency(sex_churn)

(346.54494074137529,
 2.3962837041848975e-77,
 1,
 array([[ 416.30929368,  415.69070632],
        [ 256.69070632,  256.30929368]]))

El primer valor es el valor chi cuadrado. 

El segundo valor es el p_valor.

El tercer valor son los grados de libertad.

El cuarto valor la tabla de contigencia con los valores esperados.

# ANOVA

In [116]:
churners_data_0.head()

ID  EDAD       SEXO    CIVIL  HIJOS   INGRESO                    AUTO  \
0   0    57   Femenino   Casado      2  27535.30     Es dueño de un auto   
1   4    68   Femenino   Casado      2  81000.90  No es dueño de un auto   
3  10    60  Masculino   Casado      2  83220.60  No es dueño de un auto   
4  13    28   Femenino   Casado      2  20850.40  No es dueño de un auto   
6  19    87   Femenino  Soltero      2   3776.12  No es dueño de un auto   

        CHURN  
0  Voluntario  
1  Voluntario  
3  Voluntario  
4  Voluntario  
6  Voluntario

In [117]:
churners_d1=churners_data_0[['CIVIL','INGRESO']]

In [118]:
churners_d1.groupby(['CIVIL'])['CIVIL'].count()

CIVIL
Casado     306
Soltero    207
Name: CIVIL, dtype: int64

In [121]:
churners_casado=churners_d1[churners_d1['CIVIL']=='Casado']